# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'
# workspace '../TrainingManager.xcworkspace'
target 'TrainingManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrainingManager
  pod 'Charts'
  pod 'FSCalendar'

  target 'StatsWidgetExtension' do

    pod 'Charts'

  end
end
